//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recommender.Resources.Localizations
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Recommender.Resources.Localizations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }

        public static string OnboardingContinue {
            get {
                return ResourceManager.GetString("OnboardingContinue", resourceCulture);
            }
        }

        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }

        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }

        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }

        public static string LoginContinue {
            get {
                return ResourceManager.GetString("LoginContinue", resourceCulture);
            }
        }

        public static string LoginSignUp {
            get {
                return ResourceManager.GetString("LoginSignUp", resourceCulture);
            }
        }

        public static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }

        public static string LoginEmailRequired
        {
            get
            {
                return ResourceManager.GetString("LoginEmailRequired", resourceCulture);
            }
        }

        public static string LoginEmailInvalid
        {
            get
            {
                return ResourceManager.GetString("LoginEmailInvalid", resourceCulture);
            }
        }

        public static string LoginPasswordRequired
        {
            get
            {
                return ResourceManager.GetString("LoginPasswordRequired", resourceCulture);
            }
        }

        public static string LoginPasswordInvalid
        {
            get
            {
                return ResourceManager.GetString("LoginPasswordInvalid", resourceCulture);
            }
        }

        public static string LoginFailed
        {
            get
            {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }

        public static string LoadingMessage
        {
            get
            {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
    }
}
